# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

# Book settings
title: Network Machine Learning in Python
author: Joshua Vogelstein, Alex Loftus, and Eric Bridgeford
copyright: "2021" # to be placed in the footer
logo: logo.png
parse:
  myst_enable_extensions:
    - amsmath
repository:
  url: https://github.com/neurodata/graph-stats-book
sphinx:
  extra_extensions:
    - jupyterbook_latex
    
# HTML-specific settings
html:
  navbar_number_sections: true # Add a number to each section in your left navbar
  use_edit_page_button: true
  comments:
    hypothesis: true  # to allow comments on pages. https://jupyterbook.org/interactive/comments/hypothesis.html
    
# latex settings
latex:
  latex_engine: pdflatex
