name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install wheel setuptools==61.0.0
        pip install -r requirements.txt
        mkdir -p /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graspologic/layouts/include/
        wget -O /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graspologic/layouts/include/colors-100.json https://raw.githubusercontent.com/ebridge2/graspologic/dev/graspologic/layouts/include/colors-100.json
        chmod 777 /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graspologic/layouts/include/colors-100.json
    # Build the book
    - name: Build the book
      run: |
         jupyter-book build network_machine_learning_in_python

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: network_machine_learning_in_python/_build/html
